spring.application.name=inventory-system

spring.datasource.url=jdbc:postgresql://localhost:5432/sii_db
spring.datasource.username=postgres
spring.datasource.password=Sofia079527!!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html