-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ajuste_inventario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    fecha_ajuste date NOT NULL,
    motivo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_ajuste character varying(50) COLLATE pg_catalog."default" NOT NULL,
    producto_id bigint NOT NULL,
    cantidad_ajustada integer NOT NULL,
    motivo_ajuste character varying(255) COLLATE pg_catalog."default" NOT NULL,
    usuario_id bigint,
    CONSTRAINT ajuste_inventario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(100) COLLATE pg_catalog."default",
    precio numeric(10, 2),
    stock integer,
    proveedor_id bigint,
    usuario_id bigint,
    categoria_id bigint,
    CONSTRAINT producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proveedor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contacto character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT proveedor_pkey PRIMARY KEY (id),
    CONSTRAINT ukou6oi9246xevkpv4u4r0jge2t UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.compra
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_compra timestamp(6) without time zone,
    monto_total double precision,
    proveedor_id bigint,
    usuario_id bigint,
    CONSTRAINT compra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_compra
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    precio_unitario double precision,
    compra_id bigint,
    producto_id bigint,
    CONSTRAINT detalle_compra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transaccion
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_transaccion date,
    monto double precision,
    tipo_transaccion character varying(255) COLLATE pg_catalog."default",
    compra_id bigint,
    venta_id bigint,
    CONSTRAINT transaccion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.venta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cliente_email character varying(255) COLLATE pg_catalog."default",
    cliente_nombre character varying(255) COLLATE pg_catalog."default",
    fecha_venta timestamp(6) without time zone,
    monto_total double precision,
    usuario_id bigint,
    CONSTRAINT venta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.detalle_venta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer,
    precio_unitario double precision,
    producto_id bigint,
    venta_id bigint,
    CONSTRAINT detalle_venta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descripcion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    stock integer,
    ubicacion character varying(255) COLLATE pg_catalog."default",
    producto_id bigint,
    CONSTRAINT inventario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.historial_precios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_cambio date,
    precio_anterior double precision,
    precio_nuevo double precision,
    producto_id bigint,
    CONSTRAINT historial_precios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movimiento_inventario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    fecha_movimiento date NOT NULL,
    tipo_movimiento character varying(255) COLLATE pg_catalog."default" NOT NULL,
    producto_id bigint,
    usuario_id bigint,
    CONSTRAINT movimiento_inventario_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.ajuste_inventario
    ADD CONSTRAINT fkf350e1e5athbw69uqa2vyi36d FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ajuste_inventario
    ADD CONSTRAINT fkp5nqc0o4d8w040edc43l9i748 FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT fk6vj0hd5jtfv3oe5yl4u7mvtqd FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT fkid8vjxky5juk3fnuc1sb9qarf FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT fkodqr7965ok9rwquj1utiamt0m FOREIGN KEY (categoria_id)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compra
    ADD CONSTRAINT fk5rv6m306dgdn4cn14eyhpexwu FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compra
    ADD CONSTRAINT fkpsfgo6ayx335hkqudyubw5536 FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_compra
    ADD CONSTRAINT fk8fysgqric0spig3y0hlkwe84e FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_compra
    ADD CONSTRAINT fkqwu2j7ft8a7gg1t54pllqtqas FOREIGN KEY (compra_id)
    REFERENCES public.compra (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transaccion
    ADD CONSTRAINT fk2lekmbv2pfee1b30ks3dxlq8r FOREIGN KEY (venta_id)
    REFERENCES public.venta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transaccion
    ADD CONSTRAINT fkdknfbq4qa9jykj5c6so21flqy FOREIGN KEY (compra_id)
    REFERENCES public.compra (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT fklostuvs99qor7x91k50ufof16 FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT fkhj0bf0515yg7equ11ab4xgq3f FOREIGN KEY (venta_id)
    REFERENCES public.venta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT fkmi06vmeg5th7wdow1mxcqg78e FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT fk2jpmjsxwl42blfea24vda6fs6 FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_precios
    ADD CONSTRAINT fkaa8vajlh734t4xtc7yrbho1tu FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_inventario
    ADD CONSTRAINT fkbg5mh28st2ys0jm9ob53ak1a4 FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.movimiento_inventario
    ADD CONSTRAINT fkd6bavqmj4o0mvn82ve46jac9v FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;