spring.application.name=inventory-system
spring.datasource.url=jdbc:postgresql://localhost:5432/inventario
spring.datasource.username=inventario_user
spring.datasource.password=sii-system123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html



